name:        stack-deploy
version:     0.0.0.1
synopsis:    Utilities around cloudformation templates
homepage:    https://github.com/mbj/stack-deploy
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/stack-deploy
license:     BSD3

dependencies:
- aeson                   ^>= 1.4
- aeson-pretty            ^>= 0.8
- amazonka                == 1.6.1
- amazonka-cloudformation == 1.6.1
- amazonka-core           == 1.6.1
- attoparsec              ^>= 0.13
- base                    >= 4.12 && ^>= 4.13
- bytestring              ^>= 0.10
- conduit                 ^>= 1.3
- containers              ^>= 0.6
- exceptions              ^>= 0.10
- filepath                ^>= 1.4
- hashable                >= 1.2 && ^>= 1.3
- lens                    >= 4.17 && ^>= 4.18
- mprelude                ^>= 0.0.1
- optparse-applicative    >= 0.14 && ^>= 0.15
- random                  ^>= 1.1
- source-constraints      ^>= 0.0.1
- stratosphere            >= 0.48 && < 1.0
- tasty                   ^>= 1.3
- tasty-mgolden           ^>= 0.0.1
- text                    ^>= 1.2
- text-conversions        ^>= 0.3
- time                    >= 1.8 && ^>= 1.9
- unliftio-core           ^>= 0.1
- unordered-containers    ^>= 0.2
- vector                  ^>= 0.12

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TypeFamilies

library:
  source-dirs:
  - src
  exposed-modules:
  - StackDeploy.CLI
  - StackDeploy.InstanceSpec
  - StackDeploy.Parameters
  - StackDeploy.Provider
  - StackDeploy.Stack
  - StackDeploy.Template
  - StackDeploy.Template.Code
  - StackDeploy.Types
  - StackDeploy.Utils
  - StackDeploy.Wait

tests:
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
