name:        stack-deploy
version:     0.0.0.1
synopsis:    Utilities around cloudformation templates
homepage:    https://github.com/mbj/stack-deploy
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/stack-deploy

dependencies:
- aeson                   == 1.4.5.0
- aeson-pretty            == 0.8.7
- amazonka                == 1.6.1
- amazonka-cloudformation == 1.6.1
- amazonka-core           == 1.6.1
- attoparsec              == 0.13.2.3
- base                    == 4.12.0.0
- bytestring              == 0.10.8.2
- conduit                 == 1.3.1.1
- containers              == 0.6.0.1
- exceptions              == 0.10.3
- hashable                == 1.2.7.0
- lens                    == 4.17.1
- mprelude                == 0.0.0.1
- optparse-applicative    == 0.14.3.0
- random                  == 1.1
- source-constraints      == 0.0.0.1
- stratosphere            == 0.42.0
- text                    == 1.2.3.1
- text-conversions        == 0.3.0
- time                    == 1.8.0.2
- unliftio-core           == 0.1.2.0
- unordered-containers    == 0.2.10.0
- vector                  == 0.12.0.3

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict

library:
  source-dirs:
  - src
  exposed-modules:
  - StackDeploy.CLI
  - StackDeploy.InstanceSpec
  - StackDeploy.Parameters
  - StackDeploy.Stack
  - StackDeploy.Template
  - StackDeploy.Template.Code
  - StackDeploy.Types
  - StackDeploy.Utils
  - StackDeploy.Wait

tests:
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
