build:
  haddock: false
resolver: lts-13.26
extra-deps:
- stratosphere-0.38.0
- commit: 0eb2334866d0d7af0aa148b2ac0d0095531ed946
  git: https://github.com/schirp-dso/source-constraints
- commit: 33aa6b71309793829b534fb29f6532d71c32b106
  git: https://github.com/mbj/amazonka
  subdirs:
  - amazonka-cloudformation
