build:
  haddock: false
resolver: lts-13.25
extra-deps:
- stratosphere-0.38.0
- commit: 2ef85432baaf0c7ef3c0809a802ed10ff6f48212
  git: https://github.com/schirp-dso/source-constraints
- commit: 33aa6b71309793829b534fb29f6532d71c32b106
  git: https://github.com/mbj/amazonka
  subdirs:
  - amazonka-cloudformation
