build:
  haddock: false
resolver: lts-13.26
extra-deps:
- stratosphere-0.38.0
- commit: c64f467f455f0632eeeb1efa81fa9739985136ad
  git: https://github.com/schirp-dso/source-constraints
- commit: 9ceec78602ed85de1a4b9e402b5aad680a1f6a98
  git: https://github.com/mbj/mprelude
- commit: 33aa6b71309793829b534fb29f6532d71c32b106
  git: https://github.com/mbj/amazonka
  subdirs:
  - amazonka-cloudformation
